on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Flatpak
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        run: |
          dnf -y install docker
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.vixalien.muzika.flatpak
          manifest-path: build-aux/flatpak/com.vixalien.muzika.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
