on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Flatpak Nightly
jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    strategy:
      matrix:
        # arch: [x86_64, aarch64]
        arch: [x86_64]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        if: matrix.arch == 'aarch64'
        run: |
          dnf -y install docker
      - name: Setup QEMU
        if: matrix.arch == 'aarch64'
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: com.vixalien.muzika.nightly.flatpak
          repository-name: gnome-nightly
          repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
          manifest-path: build-aux/flatpak/com.vixalien.muzika.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}-nightly
          arch: ${{ matrix.arch }}
